name: Publish package to GitHub NPM Repository
permissions:
  contents: read
  packages: write
on:
  release:
    types: [created]
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: corepack enable
      - uses: actions/setup-node@v7
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/
      - run: yarn install --immutable
      - run: npm install -g npm@latest
      - run: npm publish
